### ISSUE TITLE
Bump pyam-iamc to 1.8.0

### ISSUE THREAD

**Issue by jkikstra** [iiasa/climate-assessment#27]
Bumping up to the new version of pyam should yield a significant increase in speed when bigger files are read in.

See https://github.com/IAMconsortium/pyam/releases/tag/v1.8.0 (~3x times speed up for AR6 ensemble [from 90s down to 30s] )

**Comment by phackstock** [comment]
Looks like we should be able to upgrade with the next release after https://github.com/IAMconsortium/pyam/pull/742 got merged.

**Comment by danielhuppmann** [comment]
Hang on a second, will do a release pyam 1.9 later today...
